language: python
branches:
  only:
  - main
python:
- '3.7'
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- python setup.py install
script:
- python setup.py test
after_failure:
- cat test.log
notifications:
  slack:
    secure: PY7GyhVBacVqytImbrcyKlDY/uVDTtOMMQ8bEDnhbH9XZA7nOD0dXsEffz93tA1ldJd1+0zsnt9itqdk4pYXBMTcZ6uWE5H2j7KIYylQa2A2Sj5GC3/KjrbFGfqMAXYs+rc9rrlqYkwjztu+bnNqTDnq0Y4Pw0YlMs23NT6GlMg=
env:
  global:
  - secure: iztxqCY9N5v5Zx7wkjrU91Sa6QBHHYDaFcqBp22CnaU2LP4bWYS5oM6M3aRku8Xj9c2dgWmqyuMstAgAWTkz8ws3yLrUI50Nr+Q+RldEt+KAi2znVahgJQOQHasQwtd1IXca1i8XSUcKtCQyd3ihj3Ycw5yRLSv04EazOB0EOiU=
  - secure: RK31uyLWaMjCyDQrk8goy5HfHZNuJzqe1UjAXtkh1se7KjVacBqiYnjFj4vLio/hVPkygp9k33Ls+m7qXBkBlk1kzmr37na1z2yVjg9Wo2Nq/wtBFwGy33uVgeWOHIo2ac86XIYBQZABo+3o/Zq9ukYgRGQoyEG3c80oClHSTIk=
  - secure: dWVB5UlbkcGS/owMqppttM3kluV4/SA5ABqH1GlTnsRp7zl4TM7v+Ds/xCr7b4q+SFjEz9+mwdlqU2P/rwVfYiuKTQT/oAWaUBLgQJX8nO4GspD4cOg4okGeAsoZ993C8cUjnpeDp9aq99IpJizd0emzuncc0NzBBvIQlc2+zKA=
  - secure: VZAX92ha9Y98zIvh5WOOnjy0LAcX5Tp0QNh8sYznpa2cKtU5GM7aJPlJn5U6ChF4QFG2ayFPSzLooelz2eW/YRpUrgBFm25fDeosGs/Ws/4esCcnlxoRmwvVI1c5l0OVFbWbYT7KKINJLvEelHF9CrE8FGrehgWVzX3I2YOGLR4=
